Update action.yaml

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -1,27 +1,41 @@
-name: Check PR Body
+name: PR Check
 
 on:
   pull_request:
     types: [opened]
-
+    
 jobs:
-  check-body:
+  check:
     runs-on: ubuntu-latest
     steps:
-    - name: Get PR body
-      id: pr
-      uses: octokit/request-action@v2.x
-      with:
-        route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
-        mediaType: application/vnd.github.v3+json
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Check label and description
+        run: |
+          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
+          LABELS=$(curl --silent --show-error --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels" | jq -r '.[].name')
+          DESCRIPTION=$(curl --silent --show-error --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER" | jq -r '.body')
+          if [[ $LABELS =~ "Sanity Testing" ]] && [[ -n $DESCRIPTION ]]; then
+            echo "Checks passed"
+          else
+            echo "Checks failed"
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Get PR body
+        id: pr
+        run: |
+          PR_BODY=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json body -q '.body')
+          echo "::set-output name=body::$PR_BODY"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Check for name
-      run: |
-        BODY="${{ fromJson(steps.pr.outputs.data).body }}"
-        NAME=$(echo "$BODY" | grep -o 'name: \*[^*]*\*' | grep -o '\*[^*]*\*' | tr -d '*')
-        if [ -z "$NAME" ]; then
-          echo "Name is missing in the PR body"
-          exit 1
-        fi
+      - name: Validate PR body
+        run: |
+          REQUIRED_VALUES=("name" "namespace")
+          for value in "${REQUIRED_VALUES[@]}"; do
+            if ! echo "${{ steps.pr.outputs.body }}" | grep -q "$value"; then
+              echo "Error: '$value' not found in PR body."
+              exit 1
+            fi
+          done
+          echo "All required values found in PR body."
