Update action.yaml

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -1,39 +1,43 @@
-name: Label and PR Description Check
+name: PR Check
 
 on:
   pull_request:
-    types: [opened, reopened]
-
+    types: [opened, closed]
+    
 jobs:
-  check-label-and-description:
+  check:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Check label and description
+        run: |
+          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
+          LABELS=$(curl --silent --show-error --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels" | jq -r '.[].name')
+          DESCRIPTION=$(curl --silent --show-error --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER" | jq -r '.body')
+          if [[ $LABELS =~ "Sanity Testing" ]] && [[ -n $DESCRIPTION ]]; then
+            echo "Checks passed - contains both label and PR Body"
+          else
+            echo "Checks failed - doesn't contain either label or PR body"
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Check Label and PR Description
-      id: label_and_description_check
-      run: |
-        # Check if the PR has the desired label
-        if [[ $(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
-          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels" \
-          | jq -r '.[].name' | grep -c "Sanity Testing") -eq 0 ]]; then
-          echo "Desired label not found on the PR. Failing workflow."
-          exit 1
-        fi
-
-        # Check if the PR has a description
-        PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
-          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}" \
-          | jq -r '.body')
-        if [[ -z $PR_DESCRIPTION ]]; then
-          echo "PR description is missing. Failing workflow."
-          exit 1
-        fi
-
-    - name: Execute Workflow
-      if: ${{ steps.label_and_description_check.outcome == 'success' }}
-      run: |
-        # Add your workflow steps here
-        echo "Label and PR description present. Workflow executed."
+      - name: Check PR Body Content
+        id: pr_body_check
+        run: |
+          PR_BODY=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
+            | jq -r '.body')
+        
+          found_all=true
+          for value in "envname" "namespace"; do
+          if [[ ! $PR_BODY =~ $value ]]; then
+            echo "Value '$value' not found in PR body. Failing workflow."
+            found_all=false
+            exit 1
+          fi
+          done
+        
+          if [ "$found_all" = true ]; then
+          echo "All desired values found in PR body."
+          fi
