Update action.yaml

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -1,25 +1,21 @@
-name: "Run on Specific Label"
+name: PR Label Trigger
+ 
 on:
   pull_request:
-    types:
-      - labeled
-
+    types: [labeled]
+ 
 jobs:
-  run-on-label:
+  label_trigger:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Check for label
+      - name: Check if PR has specific label
+        if: ${{ contains(github.event.pull_request.labels.*.name, 'regression-test') }}
         run: |
-         # LABEL_NAME="regression-testing"  # Replace with your specific label
-          PR_LABELS="${{ github.event.pull_request.labels.*.name }}"
-          if echo "${PR_LABELS[@]}" | grep -q -w "$regression-testing"; then
-            echo "Regression Testing label is present. Continue with workflow..."
-            # Continue with your workflow steps here
-          else
-            echo "Regression Testing label is not present. Failing workflow..."
-            exit 1
-          fi
-          
+          # Your workflow steps here
+          echo "The PR has the specified label. Triggering actions..."
+ 
+      - name: Fail if label is not present
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'regression-test') }}
+        run: |
+          echo "The PR does not have the specified label. Failing workflow..."
+          exit 1
