Update action.yaml

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -14,11 +14,12 @@ jobs:
       - name: Check for label
         run: |
           LABEL_NAME="Regression Testing"  # Replace with your specific label
-          PR_LABELS="${{ github.event.pull_request.labels.*.LABEL_NAME }}"
+          PR_LABELS="${{ github.event.pull_request.labels.*.name }}"
           if echo "${PR_LABELS[@]}" | grep -q -w "$LABEL_NAME"; then
-            echo "Specific label is present. Continue with workflow..."
+            echo "Regression Testing label is present. Continue with workflow..."
             # Continue with your workflow steps here
           else
-            echo "Specific label is not present. Skipping workflow..."
-            exit 78
+            echo "Regression Testing label is not present. Failing workflow..."
+            exit 1
           fi
+          
